[info_general]
fecha = "2025062511"
nombre_pc = "DESKTOP-UA2DOS8"
estado_conexion = "Exito"

[sistema_operativo]
nombre = "Microsoft Windows 10 Home"
version = "10.0.19045"

[red]
ip = "172.20.112.1 192.168.56.1 10.20.48.92"
mascara = "20 24 22"
default_gateway = "10.20.48.2"

[hardware]
cpu = "Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz"
ram_gb = 7.88
disco_c_gb = 446.36
